language: node_js
node_js:
  - "5.10.1"
before_script:
  - npm install -g gulp
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - cat ./spec/coverage/**/*.info | node ./node_modules/coveralls/bin/coveralls.js
